/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import flexUnitTests.GridTileTest;
	import flexUnitTests.TestSuite;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var testUnitTests_TestSuite_obj:flexUnitTests.TestSuite;
		
		private var org_interguild_game_collision_GridTileTest_obj:flexUnitTests.GridTileTest;
	}
}